# Generated by Django 5.1.1 on 2024-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.CharField(max_length=100)),
                ('chef', models.CharField(max_length=100)),
                ('comida', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                
                
            ],
        ),
    ]
